# ENVIRONMENT NAME #############################################################
name: helper


# PYTHON PACKAGES ##############################################################
dependencies:
  - python=3.9
  - numpy
  - pyaml
  - opencv
  - pillow

